version: '3.9'
services:
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    image: leltondev/back-minefield:1.0.1
    ports:
      - "8090:8090"
    networks:
      - net-automato
  
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    image: leltondev/front-minefield:1.0.1
    ports:
      - "80:80"
    networks:
      - net-automato
networks:
  net-automato:
    driver: bridge
