version: '3.9'
services:
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
      labels:
        - project=minefield
        - autor=leltondev
        - description=back-minefield
    image: leltondev/back-minefield:latest
    ports:
      - "8090:8090"
    networks:
      - net-automato
  
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
      labels:
        - project=minefield
        - autor=leltondev
        - description=back-minefield
    image: leltondev/front-minefield:latest
    ports:
      - "80:80"
    networks:
      - net-automato
networks:
  net-automato:
    driver: bridge
